### ISSUE TITLE
Champ can maintain collections

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/kabanero-collection#13]

**Comment by stephenkinder** [comment]
@ianpartridge I think we said this morning that the documentation for how to manually build a collection is going to be delivered this iteration.  If we can write down a rough run book for that the bringup team can help get that made into the documentation that we can link to from the website for Champ.

**Comment by ianpartridge** [comment]
Yep we can create some basic doc around this.

**Comment by jgawor** [comment]
I created a readme file for using Tekton to build the collections: https://github.com/kabanero-io/collections/tree/master/ci/tekton. This could be expanded a bit I think.

**Comment by groeges** [comment]
README.md for Collections has been updated to add additional steps.

**Comment by groeges** [comment]
@marikaj123 Did we get any decision on what additional docs were needed for this. 
The README.md has been updated and also a section of the Collection repository structure has also been added. What else is required before we can close off this item?

**Comment by groeges** [comment]
All work for release 0.1 completed.
