### ISSUE TITLE
Question: Roadmap of kabanero-collections

### ISSUE THREAD

**Issue by rhuss** [kabanero-io/kabanero-collection#26]
I read your [specifications.md](https://github.com/kabanero-io/kabanero-collection/blob/master/specification.md) and it looks very interesting.

It looks like there is not much to try out yet (except some sample descriptors). Also, the client seems to be only a skeleton until now.

Is there already something like a prototype which can be tested ? Or kind of a roadmap for kabanero-collections ?

**Comment by stephenkinder** [comment]
Hi @rhuss, I apologize for the delay in responding to your question.  We should have the website updated with at least some more detail on collections, an example operator + collection activation.  This first drop will just be demonstrative of some of the concepts for the project.  I will leave this question open until I can point you at an updated website.

**Comment by stephenkinder** [comment]
An example collection was just released ... it demonstrates a collection containing a Java-MicroProfile stack.  We'll be rapidly added additional feature collections over the coming iterations.
