### ISSUE TITLE
Offline repositories and collections

### ISSUE THREAD

**Issue by jgawor** [kabanero-io/kabanero-collection#27]
Ability to easily offline the repository / collections. For example, use relative urls, etc.

**Comment by jgawor** [comment]
The `collectionUrls` may need to point to a released archive.

**Comment by jgawor** [comment]
`collection.yaml` needs to use relative urls.

**Comment by jgawor** [comment]
And use releases instead of raw links.

**Comment by marikaj123** [comment]
Is this issue opened for the collection Kabanero team?

**Comment by ianpartridge** [comment]
I am closing this for now as it lacks a clear description of the problem and exactly what actions the collections team may be required to take. Given the highly distributed nature of our work this is vital. (please reopen if you can provide some clarity)
