### ISSUE TITLE
Provide tool to re-create collection index

### ISSUE THREAD

**Issue by jgawor** [kabanero-io/kabanero-collection#28]
Target repository has changed. URLs need to be updated.

**Comment by marikaj123** [comment]
Is this issue opened for the collection Kabanero team?

**Comment by ianpartridge** [comment]
I am closing this for now as it lacks a clear description of the problem and exactly what actions the collections team may be required to take. Given the highly distributed nature of our work this is vital.

**Comment by ianpartridge** [comment]
(please reopen if you can provide some clarity)
