### ISSUE TITLE
The Kabanero collection repo, should have a readme

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/kabanero-collection#30]
The readme should be a description of what is a collection, how this repo is layed out.

**Comment by groeges** [comment]
Pull Request: https://github.com/kabanero-io/collections/pull/79 adds a repo-structure.md file that describes the directory structure of the Kabanero Collections github repository along with a description of some of the files contained within the repository. A link has been added to the README.md to point to this new file.
