### ISSUE TITLE
Add the Kabanero node (express) appsody stack to the Kabanero featured collection.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-collection#34]
Deliver the initial featured collection for node express.  We need to ensure that the operator can install the collection, and test that the manual pipeline similar to the Java-MicroProfile example here: https://github.com/kabanero-io/docs/blob/master/ref/scripts/appsody-tekton-example-manual-run.sh.

**Comment by groeges** [comment]
Delivered in Kabanero Collections v0.1.2
