### ISSUE TITLE
Add the Kabanero Java Spring Boot (Tomcat) appsody stack to the Kabanero featured collection.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-collection#35]
The Kabanero default collection does not yet contain the Java Spring Boot stack.

To validate the collection is correctly installed, we need to perform the same example build/deploy steps as demonstrated in this script: https://github.com/kabanero-io/docs/blob/master/ref/scripts/appsody-tekton-example-manual-run.sh.

**Comment by marikaj123** [comment]
Appsody stack does exit to create the application for the Spring Boot on Tomcat.
1- Need to build the collection for Spring on Tomcat.
2- Need to deliver the Tekton pipeline by the pipeline team. 
3- Need to deliver the appsody operator to deploy it.

**Comment by groeges** [comment]
Delivered in Kabanero Collections v0.1.2
