### ISSUE TITLE
Add the Kabanero Node.js (Loopback) appsody stack to the Kabanero featured collection. 

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-collection#36]
The Kabanero default collection does not yet contain the Java Spring Boot stack.

To validate the collection is correctly installed, we need to perform the same example build/deploy steps as demonstrated in this script: https://github.com/kabanero-io/docs/blob/master/ref/scripts/appsody-tekton-example-manual-run.sh.

**Comment by marikaj123** [comment]
@stephenkinder - The fix will be delivered by Aug-16.

**Comment by groeges** [comment]
Delivered in Kabanero Collections v0.1.2
