### ISSUE TITLE
Deliver the Collection for Node.js (Express)

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/kabanero-collection#4]

**Comment by marikaj123** [comment]
Appsody stack does exit to create the application for the Nodejs on Express.
1- Need to build the collection for Nodejs on Express.
2- Need to deliver the Tekton pipeline by the pipeline team. 
3- Need to deliver the appsody operator to deploy it.

**Comment by kilnerm** [comment]
I believe all outstanding items are complete.

The collection image had passed Redhat certification.

Moving to closed.
