### ISSUE TITLE
Define the Kabanero Collection build and release process

### ISSUE THREAD

**Issue by groeges** [kabanero-io/kabanero-collection#41]
Need to define how the Kabanero Collection information is to be built and released.
There is a need to piggy back off the appsody/stacks build process and to be able to release a collection in a manner that it can be easily used by all the downstream tooling.

**Comment by marikaj123** [comment]
Ian will be creating child issues for this Epic.
The team is working towards deploying Apsoddy to OpenShift.

**Comment by marikaj123** [comment]
According to Ian, the feature requires certification.

**Comment by groeges** [comment]
Done
