### ISSUE TITLE
Generate build scripts to build kabanero collection data

### ISSUE THREAD

**Issue by groeges** [kabanero-io/kabanero-collection#42]
The build scripts will be called from extension points within the appsody build scripts.
We will need to work with the Appsody team to add these extension points in the right places within their scripts.

**Comment by groeges** [comment]
Build scripts have been added to include the collection information into the index.yaml file.

Working on getting travis to run the build and to generate a release based on a tagged commit in github.

**Comment by ianpartridge** [comment]
Closing as we have the basic scripts in place.
