### ISSUE TITLE
Filter out the Swift collection

### ISSUE THREAD

**Issue by ianpartridge** [kabanero-io/kabanero-collection#47]
Currently, the published release of the collections include Swift.  As it has been decided that Swift will not be included in the initial release, we need to filter out all the Swift content from the release.

**Comment by groeges** [comment]
As part of the build process we have utilised an environment variable to exclude stacks from the build. The content of the EXCLUDED_STACKS environment variable will be a list of repo/stack elements separated by spaces which will define the stacks to exclude. 
If we had done:
```
export EXCLUDED_STACKS="incubator/swift incubator/nodejs" 
```
then when the build was run the `swift` and `nodejs` collections details would not be generated and these stacks would not be included in the index.yaml.

However, as we will not have changed the Appsody build process which this is built upon the Apposdy stacks for these excluded stacks will still be built.

**Comment by groeges** [comment]
Resolved by: https://github.com/kabanero-io/collections/pull/5

**Comment by groeges** [comment]
With the code merged for this we need to ensure that there is an EXCLUDED_STACKS environment variable set as part of our build setup. This will need to have:
```
export EXCLUDED_STACKS="incubator/swift" 
```
