### ISSUE TITLE
Doing a release of the collections should publish the images to Docker Hub

### ISSUE THREAD

**Issue by ianpartridge** [kabanero-io/kabanero-collection#48]
- [x] Get Docker Hub credentials

- [x] Update the release scripts to do the `docker push` as appropriate

**Comment by groeges** [comment]
The latest release.sh pulled in from the upstream appsody/stacks has code in it to push the docker images to dockerhub. 

This needs a couple of environment variables to be set when we do the build. These are: DOCKER_PASSWORD, DOCKER_USERNAME and DOCKER_REGISTRY (which is set to "" to use dockerhub).  

If these environment variables are set on Travis CI with the Kabanero Dockerhub credentials then the images should get pushed to dockerhub when a release is built.

**Comment by ianpartridge** [comment]
I think we probably need a way to run the build without doing the `docker push`, kind of like a "dry run" mode?

**Comment by groeges** [comment]
The build will run on a PR but will not do the release, which pushes the docker images, unless the commit is tagged. This means that we can do a build without the docker images being pushed.

**Comment by groeges** [comment]
A full release (v0.0.3) was created, including Github release and Docker images on the Kabanero Dockerhub, entirely by the automated Travis CI process. 

This all worked OK, so closing this issue.
