### ISSUE TITLE
The release process needs to run in Travis CI

### ISSUE THREAD

**Issue by ianpartridge** [kabanero-io/kabanero-collection#49]
Currently the "release" was done by hand.  We need it to run automatically in CI/CD through Travis.

- [x] Connect Travis up to the `collections` repo
- [x] Make the build run successfully and publish the assets to the GitHub release.

**Comment by jgawor** [comment]
A couple of additional concerns:
 * The build/release must use Python3 instead of Python2 (Python2 is EOL in January of 2020: https://www.python.org/dev/peps/pep-0373/)
 * The build/release must not exclusively rely on Travis. This is in consideration of enterprise users that may not have Travis available but still need to do their own builds and releases.

**Comment by groeges** [comment]
@jgawor We are initially targeting using Travis CI for this release. We know we have to investigate a build / release process that doesn't include Travis CI for Enterprise uses. For this we are going to be looking at using Tekton pipelines to do this.

I saw your PR regarding Python3. Have commented in that PR that the core CI scripts come from Appsody/stacks repo. Suggest you get your PR into that project / repo and they will then be automatically picked up in this project.

**Comment by ianpartridge** [comment]
Yep - we're going to use Travis CI for our public CI for the `collections` repo IBM publishes.  

In the initial release, customers who fork that downstream will have to run the CI script by hand and drag+drop the release assets into a GitHub release that they manually create.

In future, we want to improve that experience by providing scripting that can drive the GitHub Releases API.  And we want to support Tekton.

I also personally think that GitHub Actions should be added to the plan, as that can provide CI/CD natively for GitHub - but it's in beta at the moment and won't arrive in GHE until next year.

All this is TBC though...

**Comment by groeges** [comment]
Done
