### ISSUE TITLE
Deliver the initial set of collections

### ISSUE THREAD

**Issue by ianpartridge** [kabanero-io/kabanero-collection#50]
Over-arching epic for the initial MVP release of collections.

**Comment by marikaj123** [comment]
According to Ian, the feature requires certification for the collections getting published for the release-0.1

**Comment by groeges** [comment]
All items competed. We need final certification once we generate the final release but all certification of all previous images were OK.

**Comment by kilnerm** [comment]
Our latest collection docker images all pass RedHat certification so we should be good to close this once we cut the final branch of 0.1.2.

**Comment by groeges** [comment]
All docker images pass RedHat certification.
