### ISSUE TITLE
Write the README for the collections repo

### ISSUE THREAD

**Issue by ianpartridge** [kabanero-io/kabanero-collection#51]

**Comment by ianpartridge** [comment]
@ralanlittle has made a start on this.

**Comment by ianpartridge** [comment]
We need to write the README for how todd sets up a new kabanero index in his company.

```
$ git clone https://github.com/kabanero-io/collections.git
$ git remote add private-hub https://github.acme.com/todd/collections.git
$ git push -u private-hub
```

is the easy bit, he then needs to know how to drive the `/ci/build.sh` to generate the built collections.  Including what environment variables he needs etc.

**Comment by groeges** [comment]
First pass at describing the build process for Collections is in the README.md (https://github.com/kabanero-io/collections/blob/master/README.md)

**Comment by groeges** [comment]
Basic README on how to build the collections completed
