### ISSUE TITLE
Only the "incubator" stacks should be included in the release

### ISSUE THREAD

**Issue by ianpartridge** [kabanero-io/kabanero-collection#52]
We should not generate artifacts for "experimental" or "stable", yet.

**Comment by groeges** [comment]
The recent change in the upstream appsody/stacks  https://github.com/appsody/stacks/pull/150 for issue: https://github.com/appsody/appsody/issues/166 allows us to set an environment variable REPO_LIST that will contain the list of repos we want to process during the build. 

If we therefore set REO_LIST="incubator" then this will only build the stacks in the `incubator` repo.

**Comment by groeges** [comment]
In order to get these chnages we need to merge the upstream master branch in the appsody/stacks repo into our build-prototype branch in the kabanero-io/collections repo.

Am currently working on this but have a few merge conflicts at present. 
Will merge as soon as these are resolved.

**Comment by groeges** [comment]
Upstream merge done. PR for this is: https://github.com/kabanero-io/collections/pull/7

**Comment by groeges** [comment]
Setting the environment variable REO_LIST="incubator" allow us to only build the stacks in the incubator repo.
