### ISSUE TITLE
[Microprofile] The index.yaml contains incorrect maintainer

### ISSUE THREAD

**Issue by ianpartridge** [kabanero-io/kabanero-collection#53]
The currently published GitHub release `index.yaml` says that @groeges owns the Microprofile collection.  This isn't correct, it should list whoever is in the Appsody stack.

**Comment by groeges** [comment]
@ianpartridge I know @groeges doesn't own the Microprofile collection and this will need to change. However we shouldn't just be using the same maintainers as are defined in the stack.yaml as the collection may be maintained by someone different. 

For the moment we will use the maintainers from the stack.yaml, if there are no separate maintainers listed in the collection.yaml.

**Comment by ianpartridge** [comment]
Yep that sounds good to me. Thanks.

**Comment by groeges** [comment]
Resoled by https://github.com/kabanero-io/collections/pull/6
