### ISSUE TITLE
Error deploying node.js build pipeline

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-collection#59]
The following file:
https://github.com/kabanero-io/collections/releases/download/v0.0.4/incubator.nodejs-express.v0.2.3.pipeline.default.tar.gz

contains a build pipeline that is missing the apiVersion at the top.  The operator gets the following error when trying to deploy it:
```
Error installing the resource","resource":"https://github.com/kabanero-io/collections/releases/download/v0.0.4/incubator.nodejs-express.v0.2.3.pipeline.default.tar.gz","error":"no matches for kind \"Pipeline\" in version \"\"
```

**Comment by kvijai82** [comment]
I am in the process of creating a PR to deliver new pipelines that should fix this amongst other things tonight hopefully.

**Comment by groeges** [comment]
@kaczyns Is this still an issue with the latest collections release: https://github.com/kabanero-io/collections/releases/latest

**Comment by stephenkinder** [comment]
@kaczyns @groeges can this be closed?  Seems like it can be.
