### ISSUE TITLE
Deliver the Collection for Node.js (Loopback)

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/kabanero-collection#6]

**Comment by marikaj123** [comment]
Work will be done by August 12.

**Comment by ianpartridge** [comment]
Depends on https://github.com/appsody/stacks/pull/95

**Comment by marikaj123** [comment]
@ianpartridge - What date the fix will be available for us?

**Comment by ianpartridge** [comment]
First, the Appsody stack for Loopback needs to be delivered.  Then, that needs to be packaged into the Kabanero collection format.  The Kabanero collection format is still not agreed by the architects but we hope to make progress on that today.

**Comment by marikaj123** [comment]
Ian, according to the Appsody team, "The Loopback stack was being created by the Loopback team and not the Appsody team itself. ", do we need to remove the label 'blockedBy-Appsody'?

**Comment by marikaj123** [comment]
PR created by LoopBack team: https://github.com/appsody/stacks/pull/95.

**Comment by marikaj123** [comment]
The LoopBack team is looking to deliver the required work and get it approved by the Appsody team by end of next week.  The Collection team will be able to complete the Epic and have it included in Kabanero after.

**Comment by marikaj123** [comment]
Appsody stack does exit to create the application for the Node js on LoopBack.
1- Need to build the collection for Node js on LoopBack.
2- Need to deliver the Tekton pipeline by the pipeline team. 
3- Need to deliver the appsody operator to deploy it.

**Comment by marikaj123** [comment]
Need to have the Appsody stack. Appsody some changes from LoopBack. Appsody work needs to complete by Wednesday for Collection to complete on time. As well, Collection needs to explore the UBI image piece of work.

**Comment by marikaj123** [comment]
The expected functionality implementation for this release was provided by the LoopBack team.  Waiting for a bug fix to be resolved: https://github.com/appsody/stacks/issues/212

**Comment by groeges** [comment]
This collection has passed Redhat certification.

Moving to complete.
