### ISSUE TITLE
Problem with collection release artifacts in GitHub Enterprise 

### ISSUE THREAD

**Issue by jgawor** [kabanero-io/kabanero-collection#60]
When using GitHub Enterprise (GHE) and attaching build artifacts to a release, the GitHub-based download URLs are protected by SAML. That breaks things like Appsody or Kabanero operator from reading the index.yaml files or other artifacts.

We need an alternative solution for publishing the release artifacts.

**Comment by jgawor** [comment]
The https://github.com/appsody/stacks/pull/219 PR is a good step forward to address the issue. There are still pieces missing the satisfy the end-to-end customer scenario. That is, being able to deploy the build Docker image into the k8s cluster and being able to talk to it.

**Comment by jgawor** [comment]
Opened another related issue: https://github.com/appsody/appsody/issues/229.

**Comment by jgawor** [comment]
And another one: https://github.com/kabanero-io/kabanero-operator/issues/126

**Comment by marikaj123** [comment]
@jgawor - Jarek is providing https://github.com/kabanero-io/collections/pull/35 to fix this issue.  Collection team will merge upon agreement between Jarek and Erin.  Need to know from Jarek what other teams like operator may become impacted with this change.

**Comment by groeges** [comment]
Latest PR from @jgawor has been reviewed and merged into the collections repo.
This should allow the collection images, as well as the nginx image to be built and deployed to OpenShift using the provided Tekton pipeline.

**Comment by groeges** [comment]
Need someone with OpenShift / OKD to fully test this to ensure all is working correctly.

**Comment by groeges** [comment]
@marikaj123 Do you know whether the PR from @jgawor has been tested by anyone yet. 
We can close this issue as being delivered, but I don't want to do that until I know that what has been provided resolves the original issue.

**Comment by bconey** [comment]
Testing has been done to verify a collection repo could be successfully created with GitHub Enterprise (GHE).

**Comment by marikaj123** [comment]
@jgawor and @bconey - can the issue be closed?

**Comment by bconey** [comment]
@marikaj123 Yes, the issue can be closed.

**Comment by marikaj123** [comment]
@groeges - you have the green light to close it.

**Comment by jgawor** [comment]
Closing as testing of this change was done.
