### ISSUE TITLE
Move java-microprofile onto ubi8 base

### ISSUE THREAD

**Issue by kilnerm** [kabanero-io/kabanero-collection#61]
We are seeing issues building java-microprofile when using the current ubi7 based images. 

This sissue is open to track the work to move the stack over to ubi8.

**Comment by kilnerm** [comment]
Without this change we suspect that issues will be experienced when building the production docker images withing a tekton pipeline.

To do this I am going to need to create an interim container that is a ubi8/open-jdk/open-liberty base that I can use as a starting point for the production Docker image.

Longer term this temporary image should be pushed back into the open-liberty project.

**Comment by groeges** [comment]
@kilnerm Having the java-microprofile collection using the ubi7 images doesn't  seem to be an issue with the latest Tekton pipeline that has been produced. This is not a high priority issue.

**Comment by groeges** [comment]
Delivered in Kabanero Collections v0.1.2
