### ISSUE TITLE
Support Che on Kube with Appsody

### ISSUE THREAD

**Issue by dianak2016** [kabanero-io/kabanero-collection#64]
Kabanero would like to offer Che as a first-class deployment, managed by the Kabanero operator.  The Kabanero operator today can install Che, and the consumer can configure Che workspaces as desired.  From a Kabanero strategic point of view, it is important that the Che support includes an Appsody development experience -- at the moment, it is understood by the Kabanero team that while Che can effectively provide the Codewind experience in a hosted Kubernetes environment, the Appsody extension is not currently supported in this environment.

This makes the usage of Kabanero collections impossible in the Kabanero managed Che.

**Comment by stephenkinder** [comment]
Issue moved to [kabanero-io/kabanero-foundation #83](https://github.com/kabanero-io/kabanero-foundation/issues/83) via [**ZenHub**](https://www.zenhub.com/)
